# Generated by Django 3.1.5 on 2021-02-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crs_App', '0002_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpModel',
        ),
    ]
